# Generated by Django 4.2.5 on 2023-10-11 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_sagar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=' images'),
        ),
    ]
