# Generated by Django 4.2.5 on 2023-10-17 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_django_sagar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_sagar',
            name='gender',
            field=models.CharField(default=2, max_length=40),
            preserve_default=False,
        ),
    ]
