# Generated by Django 4.2.5 on 2023-10-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_django_sagar_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='django_sagar',
            name='gender',
            field=models.CharField(default=False, max_length=40),
        ),
    ]
