# Generated by Django 4.2.5 on 2023-10-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_django_sagar_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='django_sagar',
            name='English',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='django_sagar',
            name='Hindi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='django_sagar',
            name='Marathi',
            field=models.BooleanField(default=False),
        ),
    ]
