# Generated by Django 4.2.5 on 2023-12-13 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_order_user_address_order_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='product',
        ),
    ]
